#!/bin/bash
# ZCrystal Plugin Auto-Update Hook - Run before git push
# Usage: ./scripts/git-push.sh [git push options]
# Or: alias gitpush='/home/snow/.openclaw/workspace/zcrystal-plugin/scripts/git-push.sh'

PLUGIN_DIR="/home/snow/.openclaw/workspace/zcrystal-plugin"
cd "$PLUGIN_DIR" || exit 1

echo "🔍 Checking for new commits to push..."

# Get current branch
BRANCH=$(git branch --show-current 2>/dev/null || echo "master")

# Get the last pushed commit for this branch
LAST_PUSHED=$(git rev-parse "origin/$BRANCH" 2>/dev/null)
CURRENT=$(git rev-parse HEAD 2>/dev/null)

if [ -z "$LAST_PUSHED" ]; then
    echo "⚠️  No remote tracking found. Pushing without update."
    git push "$@"
    exit $?
fi

# Check if there are commits to push
if [ "$LAST_PUSHED" = "$CURRENT" ]; then
    echo "✅ Nothing to push (already up-to-date)"
    exit 0
fi

# Get commits since last push
COMMITS=$(git log --oneline "$LAST_PUSHED"..HEAD 2>/dev/null)
if [ -z "$COMMITS" ]; then
    echo "✅ Nothing to push"
    exit 0
fi

echo "📝 New commits detected:"
echo "$COMMITS"
echo ""

# Generate changelog entry
LATEST_COMMIT=$(echo "$COMMITS" | head -1 | awk '{print $1}')
COMMIT_COUNT=$(echo "$COMMITS" | wc -l)
DATE=$(date +"%Y-%m-%d")

# Create changelog section
CHANGELOG_SECTION="## [$DATE] - $DATE

> **Auto-generated from git log**

### Commits:
$(echo "$COMMITS" | sed 's/^/| `/' | sed 's/$/` |/')

---

"

# Check if we should update CHANGELOG (only if meaningful commits)
if echo "$COMMITS" | grep -qv "Merge"; then
    echo "📄 Updating CHANGELOG.md..."
    # Insert after the first header line
    sed -i "0,/# 更新日誌/a\\
$CHANGELOG_SECTION" CHANGELOG.md 2>/dev/null || echo "⚠️  Failed to update CHANGELOG"
fi

# Stage CHANGELOG and README changes
git add CHANGELOG.md README.md 2>/dev/null

# Check if there are changes to commit
if git diff --cached --quiet 2>/dev/null; then
    echo "✅ No documentation changes needed"
else
    echo "💾 Committing documentation updates..."
    git commit -m "docs: Auto-update CHANGELOG and README from git log
    
$(echo "$COMMITS" | head -5)
    
[Auto-generated by git-push.sh]" 2>/dev/null || echo "⚠️  Failed to commit"
fi

echo "🚀 Running git push..."
git push "$@"
exit $?